// <auto-generated />
using System;
using File_saving.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace File_saving.Migrations
{
    [DbContext(typeof(FileSavingDbContext))]
    [Migration("20240916001449_File Saving DB")]
    partial class FileSavingDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("File_saving.Models.File", b =>
                {
                    b.Property<byte[]>("File1")
                        .HasColumnType("bytea")
                        .HasColumnName("File");

                    b.Property<int?>("Id")
                        .HasColumnType("integer");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
